### ISSUE TITLE
b站视频教程下架了？

### ISSUE THREAD

**Issue by namexiaolu** [tinyRatP/Docker-Hub#5]

**Comment by vastpeng** [comment]
@namexiaolu 是的，不过通过 Docker 运行是非常简单的，README 有详细的步骤。

**Comment by namexiaolu** [comment]
> @namexiaolu 是的，不过通过 Docker 运行是非常简单的，README 有详细的步骤。
老哥，看了readme研究了半天，也不知到怎么通过docker安装，第一次接触docker。

**Comment by vastpeng** [comment]
> > @namexiaolu 是的，不过通过 Docker 运行是非常简单的，README 有详细的步骤。
> > 老哥，看了readme研究了半天，也不知到怎么通过docker安装，第一次接触docker。

1. 安装 docker 和 docker-compose
2. 创建机器人，获取用户ID，机器人简单设置（查看 README）
3. 进入 ehfor....  文件夹

```bash
docker-compose up -d # 运行服务，如果接入了 QQ，需要在网址中登录 QQ
docker logs -f efb_master # 可能需要等待一会儿，然后扫描微信二维码
docker container restart efb_master
```

**Comment by vastpeng** [comment]
@namexiaolu 

![image](https://user-images.githubusercontent.com/15377472/70375062-a080a280-1934-11ea-9ee5-05a20269a4e1.png)

依次执行命令就行了。
